name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  gradle-build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle Wrapper
        env:
          CONFIG_EXAMPLE_VALUE: ${{ secrets.CONFIG_EXAMPLE_VALUE }}
        run: ./gradlew clean build --no-daemon --info
